export enum DomainExceptionType {
    UserNotRegistered = 'UserNotRegistered',
    ProviderConflict = 'ProviderConflict',
    UserEmailConflict = 'UserEmailConflict',
    UserNotFound = 'UserNotFound',
    GetUserBadRequest = 'GetUserBadRequest',
    FriendRequestBadRequest = 'FriendRequestBadRequest',
    FriendRequestNotFound = 'FriendRequestNotFound',
    FriendRequestConflict = 'FriendRequestConflict',
    TagConflict = 'TagConflict',
    InvalidToken = 'InvalidToken',
    InvalidInput = 'InvalidInput',
    ProductCategoryNotFound = 'ProductCategoryNotFound',
    ProductNotFound = 'ProductNotFound',
    NotEnoughGold = 'NotEnoughGold',
    ProductPurchaseLimitExceeded = 'ProductPurchaseLimitExceeded',
    IslandNotFound = 'IslandNotFound',
    IslandFull = 'IslandFull',
    PlayerNotFoundInStorage = 'PlayerNotFoundInStorage',
}
